- name: Configure apt
  hosts: all
  become: true
  tasks:
    - name: Update apt package manager
      apt:
        update_cache: yes
        autoclean: yes
        upgrade: dist

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - unattended-upgrades
        - apt-listchanges
        - git
        - vim
        - curl
        - wireguard
        - wireguard-tools
        - nfs-common
        - rsync
        - tree
        - sshfs
        - rclone
        - pip
        - imagemagick

    - name: Copy unattended-upgrades configuration files in place.
      copy:
        src: ../files/02periodic
        dest: /etc/apt/apt.conf.d/02periodic
        owner: root
        group: root
        mode: 0644
