---
- name: Include OS vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure sshd is running
  service:
    name: "{{ sshd_service_name }}"
    state: "{{ sshd_service_state }}"

- name: Remove ssh host keys
  file:
    path: "/etc/ssh/{{ item }}"
    state: absent
  loop: "{{ sshd_host_keys }}"

- name: Generate new ssh host key
  openssh_keypair:
    force: true
    state: present
    type: ed25519
    path: "/etc/ssh/ssh_host_ed25519_key"

- name: Copy config file
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: sshd -T -f %s
  notify:
    - Restart sshd
    - Remove known host key

- name: Copy ntfy script
  copy:
    src: /home/ag/.local/bin/ntfy-ssh_logins
    dest: /usr/bin
    mode: 0700

- name: Configure PAM for notifcations
  lineinfile:
    insertafter: "EOF"
    path: /etc/pam.d/sshd
    line: "session optional pam_exec.so /usr/bin/ntfy-ssh_logins"
    state: present
